terms:
    - Does not apply (no collaborating organization)
    - CDC
    - US (Federal) agency other than CDC
    - Georgia state or local health department
    - State or local health department (not in Georgia)
    - Georgia state or local agency (not a health department)
    - State or local governmental agency (not a health department and not in Georgia)
    - National or regional non-profit organization (e.g., American Cancer Society)
    - Community-based non-profit organization (e.g., AID Atlanta)
    - International Non-governmental organization (e.g., CARE, Inc.)
    - International governmental organization (e.g., Agency for International Development, etc.)
    - Non-US governmental agency (e.g., Minister of Health in Haiti)
    - Emory University schools, faculty or affiliated programs
    - University, college or education institution (other than Emory)
    - Hospital or other health care provider
    - Religious-based organization
    - Industrial or Commercial (for-profit) organization
